leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
// Chang the following numbers to your liking
if (isServer ) then 
{
	// From what range away from closest player should units be cached (in meters or what every metric system arma uses)?
	// To test this set it to 20 meters. Then make sure you get that close and move away. 
	// You will notice 2 levels of caching 1 all but leader, 2 completely away
	// Stage 2 is 2 x GAIA_CACHE_STAGE_1. So default 2000, namely 2 x 1000
	GAIA_CACHE_STAGE_1				= 1000;
	// The follow 3 influence how close troops should be to known conflict to be used. (so they wont travel all the map to support)
	// How far should footmobiles be called in to support attacks.
	// This is also the range that is used by the transport system. If futher then the below setting from a zone, they can get transport.
	MCC_GAIA_MAX_SLOW_SPEED_RANGE  = 500;
	// How far should vehicles be called in to support attacks. (including boats)
	MCC_GAIA_MAX_MEDIUM_SPEED_RANGE= 4500;
	// How far should air units be called in to support attacks.
	MCC_GAIA_MAX_FAST_SPEED_RANGE  = 80000;
	// How logn should mortars and artillery wait (in seconds) between fire support missions.
	MCC_GAIA_MORTAR_TIMEOUT				 = 300;
	// DANGEROUS SETTING!!!
	// If set to TRUE gaia will even send units that she does NOT control into attacks. Be aware ONLy for attacks.
	// They will not suddenly patrol if set to true. 
	MCC_GAIA_ATTACKS_FOR_NONGAIA	 = false;
	
	// If set to false, ai will not use smoke and flares (during night)
	MCC_GAIA_AMBIANT							 = true;
	
	// Influence how high the chance is (when applicaple) that units do smokes and flare (so not robotic style)
	// Default is 20 that is a chance of 1 out of 20 when they are applicable to use smokes and flares
	MCC_GAIA_AMBIANT_CHANCE				 = 20;
	// The seconds of rest a transporter takes after STARTING his last order
	MCC_GAIA_TRANSPORT_RESTTIME		= 40;

};


// We set the markers invisible (if you use more then 100 markers, then increase). Or delete if you want them visible
for "_x" from 1 to 100 do
{
	format ["%1",_x] setMarkerAlpha 0;
};


//DO NOT CHANGE FROM BELOW (You can, but you will be out of support :P )

//----------------------gaia------------------------------------------------------
if (isserver) then {call compile preprocessfile "gaia\gaia_init.sqf";};


//===============Delete Groups ====================
if (isServer ) then 
{
	[] spawn 
	{
		_gaia_respawn = [];
		while {true} do
		{
			//player globalchat "Deleting started..............";
			
			{
				_gaia_respawn = (missionNamespace getVariable [ "GAIA_RESPAWN_" + str(_x),[] ]);
				//Store ALL original group setups
				if (count(_gaia_respawn)==0) then {[(_x)] call fn_cache_original_group;};
				
				if ((({alive _x} count units _x) == 0) ) then 
				{
					//Before we send him to heaven check if he should be reincarnated
					if (count(_gaia_respawn)==2) then {	[_gaia_respawn,(_x getVariable  ["MCC_GAIA_RESPAWN",-1]),(_x getVariable  ["MCC_GAIA_CACHE",false]),(_x getVariable  ["GAIA_zone_intend",[]])] call fn_uncache_original_group;};					
					
					//Remove the respawn group content before the group is re-used
					missionNamespace setVariable ["GAIA_RESPAWN_" + str(_x), nil];
					
					deleteGroup _x;
				};
				
				sleep .1;
				
			} foreach allGroups;			
			
			sleep 2; 
		};
	};
};

tf_no_auto_long_range_radio = true;

"patrol1" setMarkerAlphaLocal 0;
"patrol2" setMarkerAlphaLocal 0;
"patrol3" setMarkerAlphaLocal 0;

player createDiaryRecord ["Diary", 
["Equipement et supports", "Vous avez à votre disposition :<br/>- Quatre quads<br/>- Une camionette<br/>- Un offroad non armé<br/><br/>Vous ne possédez pas de radios.<br/><br/>Votre équipement est très peu fourni et vous ne possédez pas beaucoup de munitions."]];

player createDiaryRecord ["Diary", 
["Exécution", "1. Rejoindre Ioannina<br/>2. Récupérer les <marker name='obj1'>Striders</marker><br/>3. Ramener les véhicules à la base"]];

player createDiaryRecord ["Diary", 
["Mission", "Nos taupes à l'AAF ont récemment découvert que deux MRAP armés étaient actuellement en attente de transfert vers une garnison à l'Ouest de l'île, dans la petite ville de <marker name='obj1'>Ioannina</marker>.<br/>Récupérez les pour le compte de la FIA.<br/><br/>Les zones vertes désignent les dernières forces ennemies aperçues. Ces infos peuvent avoir changées.<br/>Une ou deux patrouilles ennemies peuvent être dotées de Striders.<br/>De plus, un <marker name='25'>mortier ennemi</marker> a été repéré.<br/>Les civils présents dans cette partie de l'île ont été évacués."]];

player createDiaryRecord ["Diary", 
["Situation", "Vous faites partie du groupe Est de la FIA.<br/>Vous êtes peu nombreux, et vous manquez terriblement de moyens. Heureusement, l'AAF ne vous considère pas encore comme une menace."]];

// ROSTER --------------------------------------------------------------------------------
[1,true,true] execVM "roster.sqf";

// NAMETAGS ------------------------------------------------------------------------------
TAGS = addMissionEventHandler ["Draw3D", {
    {
        if (side _x == side player && {alive _x}) then {
            _dist = (player distance _x) / 15;
            _color = getArray (configFile/'CfgInGameUI'/'SideColors'/'colorFriendly');
            if (cursorTarget != _x) then {
                _color set [3, 1 - _dist]
            };
            drawIcon3D [
                '',
                _color,
                [
                    visiblePosition _x select 0,
                    visiblePosition _x select 1,
                    (visiblePosition _x select 2) +
                    ((_x modelToWorld (
                        _x selectionPosition 'head'
                    )) select 2) + 0.4 + _dist / 1.5
                ],
                0,
                0,
                0,
                name _x,
                2,
                0.03,
                'PuristaMedium'
            ];
        };
    } count allUnits - [player];
}];
