/**
* Generated by LEA for Arma 3
* Version: 2.0.23
* Sat May 09 16:37:46 CEST 2015
* Mission file name: OuEstCharlie.Altis
* Mission name: OuEstCharlie.Altis
* Required mods:
* + TFAR
* + AGM
* + ArmA 3
* 
* Call the script: _dummy = [] execvm "lea\loadoutSingleplayer.sqf";
* 
*/

/**
* Loadout for crates
*/

//No named crates in this mission.

/**
* Loadout for soldiers units
*/

if (!isNil "HeliPilot") then {
removeallweapons HeliPilot;
removeallassigneditems HeliPilot;
removeBackpack HeliPilot;
removeVest HeliPilot;
removeHeadgear HeliPilot;
removeUniform HeliPilot;
removeGoggles HeliPilot;

HeliPilot addWeapon "ItemMap";
HeliPilot addWeapon "ItemWatch";
HeliPilot addWeapon "ItemCompass";
HeliPilot addWeapon "ItemGPS";
HeliPilot addWeapon "H_PilotHelmetHeli_I";
HeliPilot addWeapon "G_Tactical_Clear";
HeliPilot addWeapon "NVGoggles_INDEP";
HeliPilot addWeapon "Binocular";
HeliPilot addBackpack "B_TacticalPack_blk";
(backpackContainer HeliPilot) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
HeliPilot addWeapon "hgun_ACPC2_F";
removeBackpack HeliPilot;
HeliPilot addVest "V_TacVest_oli";
clearItemCargoGlobal (vestContainer HeliPilot);
clearMagazineCargoGlobal (vestContainer HeliPilot);
clearWeaponCargoGlobal (vestContainer HeliPilot);
(vestContainer HeliPilot) additemcargoGlobal ["AGM_Bandage",2];
(vestContainer HeliPilot) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer HeliPilot) additemcargoGlobal ["AGM_EarBuds",1];
HeliPilot addItemToVest "SmokeShellRed";
HeliPilot addItemToVest "SmokeShellOrange";
HeliPilot addItemToVest "SmokeShellGreen";
HeliPilot addItemToVest "SmokeShellPurple";
HeliPilot addItemToVest "SmokeShell";
HeliPilot addItemToVest "SmokeShellYellow";
HeliPilot addItemToVest "SmokeShellBlue";
HeliPilot forceAddUniform "U_I_HeliPilotCoveralls";
clearItemCargoGlobal (uniformContainer HeliPilot);
clearMagazineCargoGlobal (uniformContainer HeliPilot);
clearWeaponCargoGlobal (uniformContainer HeliPilot);
(uniformContainer HeliPilot) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",2];
HeliPilot addWeapon "tf_anprc152";
if (count weapons HeliPilot > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons HeliPilot) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     HeliPilot selectWeapon (_muzzles select 0);
  }
  else {
     HeliPilot selectWeapon _type;
  };
};
};

if (!isNil "HeliCrew") then {
removeallweapons HeliCrew;
removeallassigneditems HeliCrew;
removeBackpack HeliCrew;
removeVest HeliCrew;
removeHeadgear HeliCrew;
removeUniform HeliCrew;
removeGoggles HeliCrew;

HeliCrew addWeapon "ItemMap";
HeliCrew addWeapon "ItemWatch";
HeliCrew addWeapon "ItemCompass";
HeliCrew addWeapon "ItemGPS";
HeliCrew addWeapon "H_CrewHelmetHeli_I";
HeliCrew addWeapon "G_Aviator";
HeliCrew addWeapon "NVGoggles_INDEP";
HeliCrew addBackpack "B_TacticalPack_blk";
(backpackContainer HeliCrew) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
HeliCrew addWeapon "hgun_ACPC2_F";
removeBackpack HeliCrew;
HeliCrew addVest "V_TacVest_oli";
clearItemCargoGlobal (vestContainer HeliCrew);
clearMagazineCargoGlobal (vestContainer HeliCrew);
clearWeaponCargoGlobal (vestContainer HeliCrew);
(vestContainer HeliCrew) additemcargoGlobal ["AGM_Bandage",2];
(vestContainer HeliCrew) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer HeliCrew) additemcargoGlobal ["AGM_EarBuds",1];
HeliCrew addItemToVest "SmokeShellRed";
HeliCrew addItemToVest "SmokeShellOrange";
HeliCrew addItemToVest "SmokeShellGreen";
HeliCrew addItemToVest "SmokeShellPurple";
HeliCrew addItemToVest "SmokeShell";
HeliCrew addItemToVest "SmokeShellYellow";
HeliCrew addItemToVest "SmokeShellBlue";
HeliCrew forceAddUniform "U_I_HeliPilotCoveralls";
clearItemCargoGlobal (uniformContainer HeliCrew);
clearMagazineCargoGlobal (uniformContainer HeliCrew);
clearWeaponCargoGlobal (uniformContainer HeliCrew);
(uniformContainer HeliCrew) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",2];
HeliCrew addWeapon "tf_anprc152";
if (count weapons HeliCrew > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons HeliCrew) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     HeliCrew selectWeapon (_muzzles select 0);
  }
  else {
     HeliCrew selectWeapon _type;
  };
};
};

if (!isNil "SquadLeader") then {
removeallweapons SquadLeader;
removeallassigneditems SquadLeader;
removeBackpack SquadLeader;
removeVest SquadLeader;
removeHeadgear SquadLeader;
removeUniform SquadLeader;
removeGoggles SquadLeader;

SquadLeader addWeapon "ItemMap";
SquadLeader addWeapon "ItemWatch";
SquadLeader addWeapon "ItemCompass";
SquadLeader addWeapon "ItemGPS";
SquadLeader addWeapon "H_MilCap_dgtl";
SquadLeader addWeapon "G_Tactical_Clear";
SquadLeader addWeapon "NVGoggles_INDEP";
SquadLeader addWeapon "Binocular";
SquadLeader addBackpack "B_TacticalPack_blk";
(backpackContainer SquadLeader) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
SquadLeader addWeapon "arifle_Mk20_F";
removeBackpack SquadLeader;
SquadLeader addPrimaryWeaponItem "optic_MRCO";
SquadLeader addBackpack "B_TacticalPack_blk";
(backpackContainer SquadLeader) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
SquadLeader addWeapon "hgun_ACPC2_F";
removeBackpack SquadLeader;
SquadLeader addBackpack "tf_anprc155";
clearItemCargoGlobal (backpackContainer SquadLeader);
clearMagazineCargoGlobal (backpackContainer SquadLeader);
clearWeaponCargoGlobal (backpackContainer SquadLeader);
SquadLeader addVest "V_PlateCarrierIA2_dgtl";
clearItemCargoGlobal (vestContainer SquadLeader);
clearMagazineCargoGlobal (vestContainer SquadLeader);
clearWeaponCargoGlobal (vestContainer SquadLeader);
(vestContainer SquadLeader) additemcargoGlobal ["AGM_Bandage",4];
(vestContainer SquadLeader) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer SquadLeader) additemcargoGlobal ["AGM_EarBuds",1];
SquadLeader addItemToVest "HandGrenade";
SquadLeader addItemToVest "HandGrenade";
SquadLeader addItemToVest "SmokeShell";
SquadLeader addItemToVest "SmokeShell";
SquadLeader addItemToVest "SmokeShell";
SquadLeader forceAddUniform "U_I_OfficerUniform";
clearItemCargoGlobal (uniformContainer SquadLeader);
clearMagazineCargoGlobal (uniformContainer SquadLeader);
clearWeaponCargoGlobal (uniformContainer SquadLeader);
(uniformContainer SquadLeader) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",4];
(uniformContainer SquadLeader) addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Green",1];
SquadLeader addWeapon "tf_anprc152";
SquadLeader selectWeapon (primaryWeapon SquadLeader);
};

if (!isNil "Rifleman") then {
removeallweapons Rifleman;
removeallassigneditems Rifleman;
removeBackpack Rifleman;
removeVest Rifleman;
removeHeadgear Rifleman;
removeUniform Rifleman;
removeGoggles Rifleman;

Rifleman addWeapon "ItemMap";
Rifleman addWeapon "ItemWatch";
Rifleman addWeapon "ItemCompass";
Rifleman addWeapon "H_HelmetIA";
Rifleman addWeapon "NVGoggles_INDEP";
Rifleman addBackpack "B_TacticalPack_blk";
(backpackContainer Rifleman) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Rifleman addWeapon "arifle_Mk20_F";
removeBackpack Rifleman;
Rifleman addPrimaryWeaponItem "optic_MRCO";
Rifleman addBackpack "B_TacticalPack_blk";
(backpackContainer Rifleman) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Rifleman addWeapon "hgun_ACPC2_F";
removeBackpack Rifleman;
Rifleman addVest "V_PlateCarrierIA2_dgtl";
clearItemCargoGlobal (vestContainer Rifleman);
clearMagazineCargoGlobal (vestContainer Rifleman);
clearWeaponCargoGlobal (vestContainer Rifleman);
(vestContainer Rifleman) additemcargoGlobal ["AGM_Bandage",4];
(vestContainer Rifleman) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer Rifleman) additemcargoGlobal ["AGM_EarBuds",1];
Rifleman addItemToVest "HandGrenade";
Rifleman addItemToVest "HandGrenade";
Rifleman addItemToVest "SmokeShell";
Rifleman addItemToVest "SmokeShell";
Rifleman addItemToVest "SmokeShell";
Rifleman forceAddUniform "U_I_CombatUniform";
clearItemCargoGlobal (uniformContainer Rifleman);
clearMagazineCargoGlobal (uniformContainer Rifleman);
clearWeaponCargoGlobal (uniformContainer Rifleman);
(uniformContainer Rifleman) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",4];
(uniformContainer Rifleman) addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Green",1];
Rifleman addWeapon "tf_anprc152";
Rifleman selectWeapon (primaryWeapon Rifleman);
};

if (!isNil "Marksman") then {
removeallweapons Marksman;
removeallassigneditems Marksman;
removeBackpack Marksman;
removeVest Marksman;
removeHeadgear Marksman;
removeUniform Marksman;
removeGoggles Marksman;

Marksman addWeapon "ItemMap";
Marksman addWeapon "ItemWatch";
Marksman addWeapon "ItemCompass";
Marksman addWeapon "H_HelmetIA_camo";
Marksman addWeapon "G_Sport_Red";
Marksman addWeapon "NVGoggles_INDEP";
Marksman addBackpack "B_TacticalPack_blk";
(backpackContainer Marksman) addmagazinecargoGlobal ["10Rnd_762x54_Mag",1];
Marksman addWeapon "srifle_DMR_01_F";
removeBackpack Marksman;
Marksman addPrimaryWeaponItem "optic_DMS";
Marksman addBackpack "B_TacticalPack_blk";
(backpackContainer Marksman) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Marksman addWeapon "hgun_ACPC2_F";
removeBackpack Marksman;
Marksman addVest "V_PlateCarrierIA2_dgtl";
clearItemCargoGlobal (vestContainer Marksman);
clearMagazineCargoGlobal (vestContainer Marksman);
clearWeaponCargoGlobal (vestContainer Marksman);
(vestContainer Marksman) additemcargoGlobal ["AGM_Bandage",4];
(vestContainer Marksman) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer Marksman) additemcargoGlobal ["AGM_EarBuds",1];
Marksman addItemToVest "HandGrenade";
Marksman addItemToVest "HandGrenade";
Marksman addItemToVest "SmokeShell";
Marksman addItemToVest "SmokeShell";
Marksman addItemToVest "SmokeShell";
Marksman forceAddUniform "U_I_CombatUniform";
clearItemCargoGlobal (uniformContainer Marksman);
clearMagazineCargoGlobal (uniformContainer Marksman);
clearWeaponCargoGlobal (uniformContainer Marksman);
(uniformContainer Marksman) addmagazinecargoGlobal ["10Rnd_762x54_Mag",4];
Marksman addWeapon "tf_anprc152";
Marksman selectWeapon (primaryWeapon Marksman);
};

if (!isNil "UAVOp") then {
removeallweapons UAVOp;
removeallassigneditems UAVOp;
removeBackpack UAVOp;
removeVest UAVOp;
removeHeadgear UAVOp;
removeUniform UAVOp;
removeGoggles UAVOp;

UAVOp addWeapon "ItemMap";
UAVOp addWeapon "ItemWatch";
UAVOp addWeapon "ItemCompass";
UAVOp addWeapon "I_UavTerminal";
UAVOp addWeapon "H_HelmetIA";
UAVOp addWeapon "NVGoggles_INDEP";
UAVOp addBackpack "B_TacticalPack_blk";
(backpackContainer UAVOp) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
UAVOp addWeapon "arifle_Mk20_F";
removeBackpack UAVOp;
UAVOp addBackpack "B_TacticalPack_blk";
(backpackContainer UAVOp) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
UAVOp addWeapon "hgun_ACPC2_F";
removeBackpack UAVOp;
UAVOp addBackpack "I_UAV_01_backpack_F";
UAVOp addVest "V_PlateCarrierIA2_dgtl";
clearItemCargoGlobal (vestContainer UAVOp);
clearMagazineCargoGlobal (vestContainer UAVOp);
clearWeaponCargoGlobal (vestContainer UAVOp);
(vestContainer UAVOp) additemcargoGlobal ["AGM_Bandage",4];
(vestContainer UAVOp) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer UAVOp) additemcargoGlobal ["AGM_EarBuds",1];
UAVOp addItemToVest "HandGrenade";
UAVOp addItemToVest "HandGrenade";
UAVOp addItemToVest "SmokeShell";
UAVOp addItemToVest "SmokeShell";
UAVOp addItemToVest "SmokeShell";
UAVOp forceAddUniform "U_I_CombatUniform";
clearItemCargoGlobal (uniformContainer UAVOp);
clearMagazineCargoGlobal (uniformContainer UAVOp);
clearWeaponCargoGlobal (uniformContainer UAVOp);
(uniformContainer UAVOp) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",4];
(uniformContainer UAVOp) addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Green",1];
UAVOp addWeapon "tf_anprc152";
UAVOp selectWeapon (primaryWeapon UAVOp);
};

if (!isNil "Medic") then {
removeallweapons Medic;
removeallassigneditems Medic;
removeBackpack Medic;
removeVest Medic;
removeHeadgear Medic;
removeUniform Medic;
removeGoggles Medic;

Medic addWeapon "ItemMap";
Medic addWeapon "ItemWatch";
Medic addWeapon "ItemCompass";
Medic addWeapon "H_HelmetIA";
Medic addWeapon "NVGoggles_INDEP";
Medic addBackpack "B_TacticalPack_blk";
(backpackContainer Medic) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",1];
Medic addWeapon "arifle_Mk20_F";
removeBackpack Medic;
Medic addBackpack "B_TacticalPack_blk";
(backpackContainer Medic) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
Medic addWeapon "hgun_ACPC2_F";
removeBackpack Medic;
Medic addBackpack "B_AssaultPack_rgr";
clearItemCargoGlobal (backpackContainer Medic);
clearMagazineCargoGlobal (backpackContainer Medic);
clearWeaponCargoGlobal (backpackContainer Medic);
(backpackContainer Medic) additemcargoGlobal ["AGM_Bandage",30];
(backpackContainer Medic) additemcargoGlobal ["AGM_Epipen",5];
(backpackContainer Medic) additemcargoGlobal ["AGM_Morphine",10];
(backpackContainer Medic) additemcargoGlobal ["AGM_Bloodbag",3];
Medic addVest "V_PlateCarrierIA2_dgtl";
clearItemCargoGlobal (vestContainer Medic);
clearMagazineCargoGlobal (vestContainer Medic);
clearWeaponCargoGlobal (vestContainer Medic);
(vestContainer Medic) additemcargoGlobal ["AGM_Bandage",4];
(vestContainer Medic) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer Medic) additemcargoGlobal ["AGM_EarBuds",1];
Medic addItemToVest "HandGrenade";
Medic addItemToVest "HandGrenade";
Medic addItemToVest "SmokeShell";
Medic addItemToVest "SmokeShell";
Medic addItemToVest "SmokeShell";
Medic forceAddUniform "U_I_CombatUniform";
clearItemCargoGlobal (uniformContainer Medic);
clearMagazineCargoGlobal (uniformContainer Medic);
clearWeaponCargoGlobal (uniformContainer Medic);
(uniformContainer Medic) addmagazinecargoGlobal ["30Rnd_556x45_Stanag",4];
(uniformContainer Medic) addmagazinecargoGlobal ["30Rnd_556x45_Stanag_Tracer_Green",1];
Medic addWeapon "tf_anprc152";
Medic selectWeapon (primaryWeapon Medic);
};

if (!isNil "pSurv1") then {
removeallweapons pSurv1;
removeallassigneditems pSurv1;
removeBackpack pSurv1;
removeVest pSurv1;
removeHeadgear pSurv1;
removeUniform pSurv1;
removeGoggles pSurv1;

pSurv1 addWeapon "ItemWatch";
pSurv1 addWeapon "ItemCompass";
pSurv1 addWeapon "H_PilotHelmetHeli_I";
pSurv1 addWeapon "G_Tactical_Clear";
pSurv1 addWeapon "NVGoggles_INDEP";
pSurv1 addWeapon "Binocular";
pSurv1 addBackpack "B_TacticalPack_blk";
(backpackContainer pSurv1) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
pSurv1 addWeapon "hgun_ACPC2_F";
removeBackpack pSurv1;
pSurv1 addVest "V_TacVest_oli";
clearItemCargoGlobal (vestContainer pSurv1);
clearMagazineCargoGlobal (vestContainer pSurv1);
clearWeaponCargoGlobal (vestContainer pSurv1);
(vestContainer pSurv1) additemcargoGlobal ["AGM_Bandage",2];
(vestContainer pSurv1) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer pSurv1) additemcargoGlobal ["AGM_EarBuds",1];
pSurv1 addItemToVest "SmokeShellRed";
pSurv1 addItemToVest "SmokeShellOrange";
pSurv1 addItemToVest "SmokeShellGreen";
pSurv1 addItemToVest "SmokeShellPurple";
pSurv1 addItemToVest "SmokeShell";
pSurv1 addItemToVest "SmokeShellYellow";
pSurv1 addItemToVest "SmokeShellBlue";
pSurv1 forceAddUniform "U_I_HeliPilotCoveralls";
clearItemCargoGlobal (uniformContainer pSurv1);
clearMagazineCargoGlobal (uniformContainer pSurv1);
clearWeaponCargoGlobal (uniformContainer pSurv1);
(uniformContainer pSurv1) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",2];
if (count weapons pSurv1 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons pSurv1) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     pSurv1 selectWeapon (_muzzles select 0);
  }
  else {
     pSurv1 selectWeapon _type;
  };
};
};

if (!isNil "pSurv2") then {
removeallweapons pSurv2;
removeallassigneditems pSurv2;
removeBackpack pSurv2;
removeVest pSurv2;
removeHeadgear pSurv2;
removeUniform pSurv2;
removeGoggles pSurv2;

pSurv2 addWeapon "ItemWatch";
pSurv2 addWeapon "ItemCompass";
pSurv2 addWeapon "H_CrewHelmetHeli_I";
pSurv2 addWeapon "G_Aviator";
pSurv2 addWeapon "NVGoggles_INDEP";
pSurv2 addBackpack "B_TacticalPack_blk";
(backpackContainer pSurv2) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",1];
pSurv2 addWeapon "hgun_ACPC2_F";
removeBackpack pSurv2;
pSurv2 addVest "V_TacVest_oli";
clearItemCargoGlobal (vestContainer pSurv2);
clearMagazineCargoGlobal (vestContainer pSurv2);
clearWeaponCargoGlobal (vestContainer pSurv2);
(vestContainer pSurv2) additemcargoGlobal ["AGM_Bandage",2];
(vestContainer pSurv2) additemcargoGlobal ["AGM_Morphine",1];
(vestContainer pSurv2) additemcargoGlobal ["AGM_EarBuds",1];
pSurv2 addItemToVest "SmokeShellRed";
pSurv2 addItemToVest "SmokeShellOrange";
pSurv2 addItemToVest "SmokeShellGreen";
pSurv2 addItemToVest "SmokeShellPurple";
pSurv2 addItemToVest "SmokeShell";
pSurv2 addItemToVest "SmokeShellYellow";
pSurv2 addItemToVest "SmokeShellBlue";
pSurv2 forceAddUniform "U_I_HeliPilotCoveralls";
clearItemCargoGlobal (uniformContainer pSurv2);
clearMagazineCargoGlobal (uniformContainer pSurv2);
clearWeaponCargoGlobal (uniformContainer pSurv2);
(uniformContainer pSurv2) addmagazinecargoGlobal ["9Rnd_45ACP_Mag",2];
if (count weapons pSurv2 > 0) then {
  private['_type', '_muzzles'];
  _type = ((weapons pSurv2) select 0);
  _muzzles = getArray(configFile >>"cfgWeapons">> _type >>"muzzles");
  if (count _muzzles > 1) then {
     pSurv2 selectWeapon (_muzzles select 0);
  }
  else {
     pSurv2 selectWeapon _type;
  };
};
};

