leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
// Chang the following numbers to your liking
if (isServer ) then 
{
	// From what range away from closest player should units be cached (in meters or what every metric system arma uses)?
	// To test this set it to 20 meters. Then make sure you get that close and move away. 
	// You will notice 2 levels of caching 1 all but leader, 2 completely away
	// Stage 2 is 2 x GAIA_CACHE_STAGE_1. So default 2000, namely 2 x 1000
	GAIA_CACHE_STAGE_1				= 1000;
	// The follow 3 influence how close troops should be to known conflict to be used. (so they wont travel all the map to support)
	// How far should footmobiles be called in to support attacks.
	// This is also the range that is used by the transport system. If futher then the below setting from a zone, they can get transport.
	MCC_GAIA_MAX_SLOW_SPEED_RANGE  = 1100;
	// How far should vehicles be called in to support attacks. (including boats)
	MCC_GAIA_MAX_MEDIUM_SPEED_RANGE= 5000;
	// How far should air units be called in to support attacks.
	MCC_GAIA_MAX_FAST_SPEED_RANGE  = 80000;
	// How logn should mortars and artillery wait (in seconds) between fire support missions.
	MCC_GAIA_MORTAR_TIMEOUT				 = 300;
	// DANGEROUS SETTING!!!
	// If set to TRUE gaia will even send units that she does NOT control into attacks. Be aware ONLy for attacks.
	// They will not suddenly patrol if set to true. 
	MCC_GAIA_ATTACKS_FOR_NONGAIA	 = true;
	
	// If set to false, ai will not use smoke and flares (during night)
	MCC_GAIA_AMBIANT							 = true;
	
	// Influence how high the chance is (when applicaple) that units do smokes and flare (so not robotic style)
	// Default is 20 that is a chance of 1 out of 20 when they are applicable to use smokes and flares
	MCC_GAIA_AMBIANT_CHANCE				 = 20;
	// The seconds of rest a transporter takes after STARTING his last order
	MCC_GAIA_TRANSPORT_RESTTIME		= 40;

};


// We set the markers invisible (if you use more then 100 markers, then increase). Or delete if you want them visible
for "_x" from 1 to 100 do
{
	format ["%1",_x] setMarkerAlpha 0;
};


//DO NOT CHANGE FROM BELOW (You can, but you will be out of support :P )

//----------------------gaia------------------------------------------------------
if (isserver) then {call compile preprocessfile "gaia\gaia_init.sqf";};


//===============Delete Groups ====================
if (isServer ) then 
{
	[] spawn 
	{
		_gaia_respawn = [];
		while {true} do
		{
			//player globalchat "Deleting started..............";
			
			{
				_gaia_respawn = (missionNamespace getVariable [ "GAIA_RESPAWN_" + str(_x),[] ]);
				//Store ALL original group setups
				if (count(_gaia_respawn)==0) then {[(_x)] call fn_cache_original_group;};
				
				if ((({alive _x} count units _x) == 0) ) then 
				{
					//Before we send him to heaven check if he should be reincarnated
					if (count(_gaia_respawn)==2) then {	[_gaia_respawn,(_x getVariable  ["MCC_GAIA_RESPAWN",-1]),(_x getVariable  ["MCC_GAIA_CACHE",false]),(_x getVariable  ["GAIA_zone_intend",[]])] call fn_uncache_original_group;};					
					
					//Remove the respawn group content before the group is re-used
					missionNamespace setVariable ["GAIA_RESPAWN_" + str(_x), nil];
					
					deleteGroup _x;
				};
				
				sleep .1;
				
			} foreach allGroups;			
			
			sleep 2; 
		};
	};
};

// DISABLE TASK FORCE RADIO AUTO LONG RANGE (Sergeant and above)
tf_no_auto_long_range_radio = true;

//=================== BRIEFING

player createDiaryRecord ["Diary", 
["Situation", "Il y a quelques minutes, un hélicoptère de combat Kajman de l'AAF, nom de code Charlie, s'est écrasé sur Altis, suite à un dysfonctionnement moteur, en plein territoire de la FIA.<br/>D'après les communications FIA interceptées, les deux membres d'équipages seraient encore en vie. Nous ne pouvons pas permettre à la FIA de capturer et interroger Charlie.<br/><br/>Vous faites partie d'un détachement chargé de les sauver.<br/>Ce détachement est composé d'une équipe de 5 hommes, dont un opérateur drone (Bravo), ainsi que d'un hélicoptère de transport Hellcat non armé et de son équipage (Alpha).<br/><br/>Il semblerait que Charlie ne possède pas de moyens de nous contacter."]];

player createDiaryRecord ["Diary", 
["Mission", "Alpha et Bravo devront se coordonner dans le but de ramener sains et sauf Charlie à la base. D'après la reconnaissance effectuée par Charlie avant le crash, le terrain est patrouillé par plusieurs équipes de la FIA.<br/>Par ailleurs, aucun engin anti-aérien n'a été reporté, et très peu de véhicules ennemis sont présents."]];

player createDiaryRecord ["Diary", 
["Execution", "Alpha et Bravo : Déclencher le trigger radio Alpha en début de partie pour recevoir la position du crash de Charlie. Déployez-vous ensuite au plus vite pour les retrouver.<br/><br/>Charlie : Le crash a de toute évidence été repéré par la FIA, et il est fort probable qu'une patrouille arrivera sous peu pour vérifier l'épave."]];

player createDiaryRecord ["Diary", 
["Environnement", "La météo prévoit de rester clémente dans les prochaines heures."]];

if(isServer) then {

	
	
	//smoke1 = "test_EmptyObjectForSmoke" createVehicle position Kajman; smoke1 setpos (getpos Kajman);
};