leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
// GAIA ----------------------------------------------------------------------------------
// Chang the following numbers to your liking
if (isServer ) then 
{
	// From what range away from closest player should units be cached (in meters or what every metric system arma uses)?
	// To test this set it to 20 meters. Then make sure you get that close and move away. 
	// You will notice 2 levels of caching 1 all but leader, 2 completely away
	// Stage 2 is 2 x GAIA_CACHE_STAGE_1. So default 2000, namely 2 x 1000
	GAIA_CACHE_STAGE_1				= 2000;
	// The follow 3 influence how close troops should be to known conflict to be used. (so they wont travel all the map to support)
	// How far should footmobiles be called in to support attacks.
	// This is also the range that is used by the transport system. If futher then the below setting from a zone, they can get transport.
	MCC_GAIA_MAX_SLOW_SPEED_RANGE  = 500;
	// How far should vehicles be called in to support attacks. (including boats)
	MCC_GAIA_MAX_MEDIUM_SPEED_RANGE= 5000;
	// How far should air units be called in to support attacks.
	MCC_GAIA_MAX_FAST_SPEED_RANGE  = 80000;
	// How logn should mortars and artillery wait (in seconds) between fire support missions.
	MCC_GAIA_MORTAR_TIMEOUT				 = 300;
	// DANGEROUS SETTING!!!
	// If set to TRUE gaia will even send units that she does NOT control into attacks. Be aware ONLy for attacks.
	// They will not suddenly patrol if set to true. 
	MCC_GAIA_ATTACKS_FOR_NONGAIA	 = false;
	
	// If set to false, ai will not use smoke and flares (during night)
	MCC_GAIA_AMBIANT							 = true;
	
	// Influence how high the chance is (when applicaple) that units do smokes and flare (so not robotic style)
	// Default is 20 that is a chance of 1 out of 20 when they are applicable to use smokes and flares
	MCC_GAIA_AMBIANT_CHANCE				 = 20;
	// The seconds of rest a transporter takes after STARTING his last order
	MCC_GAIA_TRANSPORT_RESTTIME		= 40;

};


// We set the markers invisible (if you use more then 100 markers, then increase). Or delete if you want them visible
for "_x" from 1 to 100 do
{
	format ["%1",_x] setMarkerAlpha 0;
};


//DO NOT CHANGE FROM BELOW (You can, but you will be out of support :P )

//----------------------gaia------------------------------------------------------
if (isserver) then {call compile preprocessfile "gaia\gaia_init.sqf";};


//===============Delete Groups ====================
if (isServer ) then 
{
	[] spawn 
	{
		_gaia_respawn = [];
		while {true} do
		{
			//player globalchat "Deleting started..............";
			
			{
				_gaia_respawn = (missionNamespace getVariable [ "GAIA_RESPAWN_" + str(_x),[] ]);
				//Store ALL original group setups
				if (count(_gaia_respawn)==0) then {[(_x)] call fn_cache_original_group;};
				
				if ((({alive _x} count units _x) == 0) ) then 
				{
					//Before we send him to heaven check if he should be reincarnated
					if (count(_gaia_respawn)==2) then {	[_gaia_respawn,(_x getVariable  ["MCC_GAIA_RESPAWN",-1]),(_x getVariable  ["MCC_GAIA_CACHE",false]),(_x getVariable  ["GAIA_zone_intend",[]])] call fn_uncache_original_group;};					
					
					//Remove the respawn group content before the group is re-used
					missionNamespace setVariable ["GAIA_RESPAWN_" + str(_x), nil];
					
					deleteGroup _x;
				};
				
				sleep .1;
				
			} foreach allGroups;			
			
			sleep 2; 
		};
	};
};

//=================== BRIEFING

player createDiaryRecord ["Diary", 
["Changelog", "13/08/16<br/>- Fix bug du vent<br/>- Ajout CAS<br/>- Amélioration de l'IA<br/>- enableDebugConsole :)"]];

player createDiaryRecord ["Diary", 
["Environnement", "Il est 03h30, il fait nuit. Vous disposez de moins d'une heure avant les premiers rayons du soleil."]];

player createDiaryRecord ["Diary", 
["Equipement et supports", "Vous disposez pour cette mission de deux SDV.<br/><br/>En cas de difficulté, vous avez l'option d'appeler un CAS sur la position du camion pour le détruire (via trigger radio). Utiliser cette option est un dernier recours et la mission sera alors considérée comme un échec."]];

player createDiaryRecord ["Diary", 
["Exécution", "Vous serez insérés en combinaisons de plongée à côté d'un chalutier civil.<br/><br/>1. Rendez-vous sur le complexe hotelier.<br/>2. Eliminez Stavrou et détruisez le camion d'armes.<br/>3. Retournez au point d'insertion.<br/><br/>N'importe qui peut stopper la mission via un trigger radio."]];

player createDiaryRecord ["Diary", 
["Renseignements", "- Nous n'avons pas d'informations sur les forces ennemies présentes. Attendez-vous à ce que la zone de transaction et ses alentours soient patrouillés."]];

player createDiaryRecord ["Diary", 
["Objectif secondaire", "Le trafiquant est apparemment arrivé sur les lieux avec un camion rempli d'armes volé récemment à l'AAF. Détruisez-le."]];

player createDiaryRecord ["Diary", 
["Objectif", "Nous savons qu'une rencontre entre Stavrou, un leader de la FIA, et un trafiquant d'armes doit avoir lieu sur le complexe hotelier désaffecté au nord-est d'Altis.<br/>Votre objectif principal est d'assassiner Stavrou."]];

player createDiaryRecord ["Diary", 
["Situation", "Le CSAT a pris possession d'Altis, mais des poches de rebelles de la FIA composées de locaux et d'anciens membres de l'OTAN s'organisent.<br/>Vous faites partie d'une équipe de plongeurs de la CSAT envoyés perturber un échange d'armes sur un complexe hotelier."]];


// ROSTER --------------------------------------------------------------------------------
[0,true,true] execVM "roster.sqf";

initDone = 1;
