leaFunction =  compile preprocessFileLineNumbers "lea\loadout-init.sqf"; call leaFunction;//line generated by LEA.
//BRIEFING

player createDiaryRecord ["Diary", 
["Eddy Malou", "Eddy Malou se trouve dans une des cellules de la prison.<br/>En l'approchant, une action molette apparaîtra, vous permettant de lui faire rejoindre et suivre votre groupe. Le leader du groupe pourra par ailleurs lui donner des ordres. Vous pouvez aussi essayer de lui donner une arme, mais étant de nature plutôt pacifiste, il est probable que la plupart de ses tirs ne toucheront pas au but.<br/>S'il vous embête vraiment, vous avez aussi du Serflex.<br/>Il s'agit de l'unique prisonnier de la prison, vous ne pourrez donc pas vous tromper."]];

player createDiaryRecord ["Diary", 
["Environnement", "Il fait nuit noir sur Imrali."]];

player createDiaryRecord ["Diary", 
["Possibilités", "Deux possibilités s'offrent à vous pour faciliter l'assaut de la prison : <br/>- Une très faible quantité de troupes a été repérée près de la tour de communication au Nord, la laissant quasiment sans défense. Détruire la tour forcerait la base de la prison à y envoyer des renforts..<br/>- L'infrastructure énergétique de la base a beaucoup souffert suite aux dernières intempéries. Par des calculs compliqués, Stephen Hawking a déterminé que détruire deux transformateurs situés à l'est de la prison provoquerait l'extinction de toutes les lumières de l'île, vous donnant ainsi l'avantage grâce à vos JVN.<br/>- Les soldats de l'OTAN sont sales, et doivent se changer de façon régulière. Stephen Hawking a ainsi découvert grâce à sa reconnaissance satellite qu'un arrivage de tenues ennemies attend son transport sur l'aérodrome de l'île. Les transports ne partiront que demain matin, vous pouvez donc essayer d'y voler un uniforme. Ainsi déguisés, vous pourrez accéder à l'intérieur de la base sous le nez de l'ennemi. Attention cependant, s'approcher trop près du bâtiment de la prison ou de la tour de communication éveillera les soupçons. De la même façon, un tir mal placé fera sauter votre couverture."]];

player createDiaryRecord ["Diary", 
["Mission", "Vous êtes payés pour récupérer Eddy Malou et le ramener sain et sauf au petit phare proche de votre zone d'insertion. Un transport viendra tous vous récupérer plus tard dans la matinée.<br/>En attendant, vous disposez de trois quads amenés il y a plusieurs jours par des contrebandiers pour vous déplacer."]];

player createDiaryRecord ["Diary", 
["Situation", "Vous faites partie d'un petit groupe de mercenaires financés par Stephen Hawking pour libérer Eddy Malou de la prison d'Imrali, emprisonné suite à la publication de ses recherches sur la nucléarité des rollers.<br/><br/>Nous savons que le secteur est très fortement défendu par plusieurs unités de l'OTAN. La présence de MRAP ennemis est plus que probable, et le large de la côte de la prison est patrouillé par des bateaux."]];

// Chang the following numbers to your liking
if (isServer ) then 
{
	// From what range away from closest player should units be cached (in meters or what every metric system arma uses)?
	// To test this set it to 20 meters. Then make sure you get that close and move away. 
	// You will notice 2 levels of caching 1 all but leader, 2 completely away
	// Stage 2 is 2 x GAIA_CACHE_STAGE_1. So default 2000, namely 2 x 1000
	GAIA_CACHE_STAGE_1				= 1500;
	// The follow 3 influence how close troops should be to known conflict to be used. (so they wont travel all the map to support)
	// How far should footmobiles be called in to support attacks.
	// This is also the range that is used by the transport system. If futher then the below setting from a zone, they can get transport.
	MCC_GAIA_MAX_SLOW_SPEED_RANGE  = 1000;
	// How far should vehicles be called in to support attacks. (including boats)
	MCC_GAIA_MAX_MEDIUM_SPEED_RANGE= 5000;
	// How far should air units be called in to support attacks.
	MCC_GAIA_MAX_FAST_SPEED_RANGE  = 80000;
	// How logn should mortars and artillery wait (in seconds) between fire support missions.
	MCC_GAIA_MORTAR_TIMEOUT				 = 300;
	// DANGEROUS SETTING!!!
	// If set to TRUE gaia will even send units that she does NOT control into attacks. Be aware ONLy for attacks.
	// They will not suddenly patrol if set to true. 
	MCC_GAIA_ATTACKS_FOR_NONGAIA	 = false;
	
	// If set to false, ai will not use smoke and flares (during night)
	MCC_GAIA_AMBIANT							 = true;
	
	// Influence how high the chance is (when applicaple) that units do smokes and flare (so not robotic style)
	// Default is 20 that is a chance of 1 out of 20 when they are applicable to use smokes and flares
	MCC_GAIA_AMBIANT_CHANCE				 = 20;
	// The seconds of rest a transporter takes after STARTING his last order
	MCC_GAIA_TRANSPORT_RESTTIME		= 40;

};


// We set the markers invisible (if you use more then 100 markers, then increase). Or delete if you want them visible
for "_x" from 1 to 100 do
{
	format ["%1",_x] setMarkerAlpha 0;
};


//DO NOT CHANGE FROM BELOW (You can, but you will be out of support :P )

//----------------------gaia------------------------------------------------------
if (isserver) then {call compile preprocessfile "gaia\gaia_init.sqf";};


//===============Delete Groups ====================
if (isServer ) then 
{
	[] spawn 
	{
		_gaia_respawn = [];
		while {true} do
		{
			//player globalchat "Deleting started..............";
			
			{
				_gaia_respawn = (missionNamespace getVariable [ "GAIA_RESPAWN_" + str(_x),[] ]);
				//Store ALL original group setups
				if (count(_gaia_respawn)==0) then {[(_x)] call fn_cache_original_group;};
				
				if ((({alive _x} count units _x) == 0) ) then 
				{
					//Before we send him to heaven check if he should be reincarnated
					if (count(_gaia_respawn)==2) then {	[_gaia_respawn,(_x getVariable  ["MCC_GAIA_RESPAWN",-1]),(_x getVariable  ["MCC_GAIA_CACHE",false]),(_x getVariable  ["GAIA_zone_intend",[]])] call fn_uncache_original_group;};					
					
					//Remove the respawn group content before the group is re-used
					missionNamespace setVariable ["GAIA_RESPAWN_" + str(_x), nil];
					
					deleteGroup _x;
				};
				
				sleep .1;
				
			} foreach allGroups;			
			
			sleep 2; 
		};
	};
};

{ 
    if(side _x == west) then 
    { 
        _x unassignItem "NVGoggles"; 
        _x removeItem "NVGoggles"; 
    }; 
} foreach (allUnits); 

initDone = 1;
